using ShibaGTGenesis.Classes;
using UnityEngine;
using static ShibaGTGenesis.Menu.Menu;

namespace ShibaGTGenesis.Menu
{
    public class Buttons
    {
        public static ButtonInfo[][] buttons = new ButtonInfo[][]
        {
            new ButtonInfo[] { // Main Page | 0
                new ButtonInfo { buttonText = "Save Enabled Buttons", method =() => Settings.SaveEnabledButtons(), isTogglable = false, toolTip = "Automatically enables all enabled mods on next boot!", sendnoti = true },
                new ButtonInfo { buttonText = "Settings", method =() => Instance.ChangeCat(true, 1), isTogglable = false, toolTip = "settings!", sendnoti = true },
                new ButtonInfo { buttonText = "OP Mods", method =() => Instance.ChangeCat(true, 2), isTogglable = false, toolTip = "op mods!", sendnoti = true },
                new ButtonInfo { buttonText = "Room Mods", method =() => Instance.ChangeCat(true, 3), isTogglable = false, toolTip = "room mods!", sendnoti = true },
                new ButtonInfo { buttonText = "World Mods", method =() => Instance.ChangeCat(true, 4), isTogglable = false, toolTip = "world mods!", sendnoti = true },
                new ButtonInfo { buttonText = "Visual Mods", method =() => Instance.ChangeCat(true, 5), isTogglable = false, toolTip = "visual mods!", sendnoti = true },
                new ButtonInfo { buttonText = "Player / Movement Mods", method =() => Instance.ChangeCat(true, 6), isTogglable = false, toolTip = "player mods!", sendnoti = true },
                new ButtonInfo { buttonText = "Legit Mods", method =() => Instance.ChangeCat(true, 7), isTogglable = false, toolTip = "legit mods!" },
                new ButtonInfo { buttonText = "Rig Mods", method =() => Instance.ChangeCat(true, 8), isTogglable = false, toolTip = "rig mods!", sendnoti = true },
                new ButtonInfo { buttonText = "Advantage Mods", method =() => Instance.ChangeCat(true, 9), isTogglable = false, toolTip = "advantage mods!", sendnoti = true },
            },

            new ButtonInfo[] { // Settings | 1
                new ButtonInfo { buttonText = "Settings", method =() => Instance.ChangeCat(false), isTogglable = false, toolTip = "Go back!" },
                new ButtonInfo { buttonText = "Save Preferences", isTogglable = false, method =() => Settings.SavePreferences(), toolTip = "Save your settings!" },
                new ButtonInfo { buttonText = "Right Hand Menu", isTogglable = true, enableMethod =() => Instance.rightHanded = true, disableMethod  =() => Instance.rightHanded = false, toolTip = "righthand!" },
                new ButtonInfo { buttonText = "Change Menu Layout: ShibaGT", method =() => Settings.ChangeLayout(false), isTogglable = false, enabled = false, toolTip = "Change layout!" },
                new ButtonInfo { buttonText = "Change Menu Theme: Dark", method =() => Settings.ChangeMenuTheme(false), enabled = false, toolTip = "Change theme!" },
                new ButtonInfo { buttonText = "Change Speed Boost: Mosa / Legit", method =() => Settings.ChangeSpeedboost(false), enabled = false, toolTip = "Change speed!" },
                new ButtonInfo { buttonText = "Lowercase Menu", method =() => Settings.LowercaseMenu(), disableMethod =() => Settings.OFFLowercaseMenu(), isTogglable = true, toolTip = "makes the menu lowercase!"},
                new ButtonInfo { buttonText = "Uppercase Menu", method =() => Settings.UppercaseMenu(), disableMethod =() => Settings.OFFUppercaseMenu(), isTogglable = true, toolTip = "makes the menu upercase!"},
                new ButtonInfo { buttonText = "Freeze When In Menu", method =() => Settings.FreezeIn(), disableMethod =() => Settings.AllowMovement(), isTogglable = true, toolTip = "makes you freeze when menu open!"},
                new ButtonInfo { buttonText = "Move Menu Status Gun", method =() => Settings.MoveStatusGun(), isTogglable = true, toolTip = "mmoves status!"},
                new ButtonInfo { buttonText = "Disable Menu Status In Stump", method =() => Settings.DisableStatus(), disableMethod =() => Settings.OFFDisableStatus(), isTogglable = true, toolTip = "Rainbow!"},
                new ButtonInfo { buttonText = "Disable Button Sounds", method =() => Settings.DisableButtonSound(), disableMethod =() => Settings.OFFDisableButtonSound(), isTogglable = true, toolTip = "disables button sounds!"},
            },

            new ButtonInfo[] { // OP Mods | 2
                new ButtonInfo { buttonText = "OP Mods", method =() => Instance.ChangeCat(false), isTogglable = false, toolTip = "Go back!" },
                new ButtonInfo { buttonText = "Antiban", method =() => OPMods.AntiBan(), isTogglable = false, toolTip = "Antiban!" },
                new ButtonInfo { buttonText = "Antiban Status", method =() => OPMods.AntiBanStatus(), isTogglable = false, toolTip = "Antiban!" },
                new ButtonInfo { buttonText = "Set Master", method =() => OPMods.SetMaster(), isTogglable = false, toolTip = "set master!" },
                new ButtonInfo { buttonText = "Auto Set Master", method =() => OPMods.AutoSetMaster(), isTogglable = true, toolTip = "set master automaticly!" },
                new ButtonInfo { buttonText = "Lag Gun", method =() => OPMods.LagGun(), isTogglable = true, toolTip = "crashes everyone!" },
                new ButtonInfo { buttonText = "Lag All", method =() => OPMods.LagAll(), isTogglable = true, toolTip = "crashes everyone!" },
                new ButtonInfo { buttonText = "Lag On Touch", method =() => OPMods.LagOnTouch(), isTogglable = true, toolTip = "crashes when someone touches u!" },
                new ButtonInfo { buttonText = "Lag On YOU Touch", method =() => OPMods.LagOnYouTouch(), isTogglable = true, toolTip = "crashes someone that u touch!" },
                new ButtonInfo { buttonText = "Lag Aura", method =() => OPMods.LagAura(), isTogglable = true, toolTip = "crash!" },
                new ButtonInfo { buttonText = "Crash Gun", method =() => OPMods.CrashGun(), isTogglable = true, toolTip = "crash!" },
                new ButtonInfo { buttonText = "Crash All", method =() => OPMods.CrashAll(), isTogglable = true, toolTip = "crash!" },
                new ButtonInfo { buttonText = "Crash On Touch", method =() => OPMods.CrashOnTouch(), isTogglable = true, toolTip = "crashes when someone touches u!" },
                new ButtonInfo { buttonText = "Crash On YOU Touch", method =() => OPMods.CrashOnYouTouch(), isTogglable = true, toolTip = "crashes someone that u touch!" },
                new ButtonInfo { buttonText = "Crash Aura", method =() => OPMods.CrashAura(), isTogglable = true, toolTip = "crashes someone that u touch!" },
                new ButtonInfo { buttonText = "Mat Spam All", method =() => OPMods.MatSpamAll(), isTogglable = true, toolTip = "Spams materials!" },
                new ButtonInfo { buttonText = "Mat Spam Gun", method =() => OPMods.MatSpamGun(), isTogglable = true, toolTip = "Spams materials on a player!" },
                new ButtonInfo { buttonText = "Break Gamemode", method =() => OPMods.BreakGamemode(), isTogglable = true, toolTip = "Breaks the game / tag!" },
                new ButtonInfo { buttonText = "Change Gamemode To Infection", method =() => OPMods.ChangeGamemode("INFECTION"), isTogglable = true, toolTip = "Change gamemode!" },
                new ButtonInfo { buttonText = "Change Gamemode To Casual", method =() => OPMods.ChangeGamemode("CASUAL"), isTogglable = true, toolTip = "Change gamemode!" },
                new ButtonInfo { buttonText = "Change Gamemode To Hunt", method =() => OPMods.ChangeGamemode("HUNT"), isTogglable = true, toolTip = "Change gamemode!" },
                new ButtonInfo { buttonText = "Change Gamemode To Battle", method =() => OPMods.ChangeGamemode("BATTLE"), isTogglable = true, toolTip = "Change gamemode!" },
                new ButtonInfo { buttonText = "Name Change All", method =() => OPMods.ChangeNameAll(), isTogglable = true, toolTip = "Name changer!" },
                new ButtonInfo { buttonText = "Name Change Gun", method =() => OPMods.ChangeNameGun(), isTogglable = true, toolTip = "Name changer!" },
                new ButtonInfo { buttonText = "Disable Network Trigger [ss]", method =() => OPMods.DisableNetworkTriggersSS(), isTogglable = true, toolTip = "network triggerssre!" },
                new ButtonInfo { buttonText = "Clear Prefabs", method =() => OPMods.ClearPrefabs(), isTogglable = false, toolTip = "Clear!" },
                new ButtonInfo { buttonText = "Ban Gun", method =() => OPMods.BanGun(), isTogglable = true, toolTip = "Ban!" },
                new ButtonInfo { buttonText = "Ban All", method =() => OPMods.BanAll(), isTogglable = false, toolTip = "Ban!" },
            },

            new ButtonInfo[] { // Room Mods | 3
                new ButtonInfo { buttonText = "Room Mods", method =() => Instance.ChangeCat(false), isTogglable = false, toolTip = "Go back!" },
                new ButtonInfo { buttonText = "Join Code GENESIS", method =() => RoomMods.JoinGenesis(), isTogglable = false, toolTip = "Join the menus code!" },
                new ButtonInfo { buttonText = "B to Disconnect", method =() => RoomMods.BDisconnect(), isTogglable = true, toolTip = "B to leave!" },
                new ButtonInfo { buttonText = "Join Random Room", method =() => RoomMods.JoinRandomRoom(), isTogglable = false, toolTip = "Join a room!" },
                new ButtonInfo { buttonText = "Create Public Room", method =() => RoomMods.CreatePublicRoom(), isTogglable = false, toolTip = "Create Public!" },
                new ButtonInfo { buttonText = "Rejoin Last Joined Lobby", method =() => RoomMods.RejoinLastRoom(), isTogglable = false, toolTip = "Rejoin!" },
                new ButtonInfo { buttonText = "Serverhop", method =() => RoomMods.Serverhop(), isTogglable = false, toolTip = "Serverhop!" },
                new ButtonInfo { buttonText = "Reconnect", method =() => RoomMods.Rejoin(), isTogglable = false, toolTip = "rejoin!" },
                new ButtonInfo { buttonText = "Cancel Reconnect", method =() => RoomMods.CancelRejoin(), isTogglable = false, toolTip = "rejoin!" },
                new ButtonInfo { buttonText = "Disable Network Triggers [cs]", method =() => RoomMods.DisableNetworkTriggers(), disableMethod =() => RoomMods.EnableNetworkTriggers(), isTogglable = true, toolTip = "Go into other maps in pubs!" },
                new ButtonInfo { buttonText = "Visible Network Triggers [cs]", method =() => RoomMods.VisibleTrigs(), disableMethod =() => RoomMods.NonVisTrigs(), isTogglable = true, toolTip = "Go into other maps in pubs!" },
                new ButtonInfo { buttonText = "AntiReport", method =() => RoomMods.AntiReport(), isTogglable = true, toolTip = "Antireport!" },
                new ButtonInfo { buttonText = "Mute Gun", method =() => RoomMods.MuteGun(), isTogglable = true, toolTip = "ez!" },
                new ButtonInfo { buttonText = "Mute All", method =() => RoomMods.MuteAll(), isTogglable = true, toolTip = "ez!" },
                new ButtonInfo { buttonText = "Unmute Gun", method =() => RoomMods.UnmuteGun(), isTogglable = true, toolTip = "ez!" },
                new ButtonInfo { buttonText = "Unmute All", method =() => RoomMods.UnmuteAll(), isTogglable = true, toolTip = "ez!" },
                new ButtonInfo { buttonText = "Hide Name On Leaderboard", method =() => RoomMods.HideNameOnLeaderboard(), isTogglable = false, toolTip = "Hide!" },
                new ButtonInfo { buttonText = "Anti Moderator", method =() => RoomMods.AntiModerator(), isTogglable = false, toolTip = "Hide!" },
                new ButtonInfo { buttonText = "ShibaGT Genesis Name", method =() => RoomMods.GenesisName(), isTogglable = true, toolTip = "genesisname!" },
                new ButtonInfo { buttonText = "Flashing ShibaGT Genesis Name", method =() => RoomMods.FlashGenesisName(), isTogglable = true, toolTip = "genesisname!" },
            },

            new ButtonInfo[] { // World Mods | 4
                new ButtonInfo { buttonText = "World Mods", method =() => Instance.ChangeCat(false), isTogglable = false, toolTip = "Go back!" },
                new ButtonInfo { buttonText = "No Gravity", method =() => WorldMods.NoGravity(), isTogglable = true, toolTip = "No gravity!" },
                new ButtonInfo { buttonText = "Low Gravity", method =() => WorldMods.LowGravity(), isTogglable = true, toolTip = "Low gravity, like the moon!" },
                new ButtonInfo { buttonText = "High Gravity", method =() => WorldMods.HighGravity(), isTogglable = true, toolTip = "High gravity!" },
                new ButtonInfo { buttonText = "Reverse Gravity", method =() => WorldMods.ReverseGravity(), isTogglable = true, toolTip = "only vr!" },
                new ButtonInfo { buttonText = "Gravity Wind", method =() => WorldMods.GravityWind(), isTogglable = true, toolTip = "Random!" },
                new ButtonInfo { buttonText = "Gravity Switcher [g]", method =() => WorldMods.GravitySwitcher(), isTogglable = true, toolTip = "Switcher!" },
                new ButtonInfo { buttonText = "Blind Gun", method =() => WorldMods.BlindGun(), isTogglable = true, toolTip = "targets!" },
                new ButtonInfo { buttonText = "Blind All", method =() => WorldMods.BlindAll(), isTogglable = true, toolTip = "targets!" },
                new ButtonInfo { buttonText = "L Cubebending", method =() => WorldMods.Lcubebending(), isTogglable = true, toolTip = "grip bend!" },
                new ButtonInfo { buttonText = "R Cubebending", method =() => WorldMods.Rcubebending(), isTogglable = true, toolTip = "grip bend!" },
                new ButtonInfo { buttonText = "Cube Player Aura [lt]", method =() => WorldMods.CubePlayerAura(), isTogglable = true, toolTip = "aura!" },
                new ButtonInfo { buttonText = "Cube Aura [lt]", method =() => WorldMods.CubeAura(), isTogglable = true, toolTip = "aura!" },
                new ButtonInfo { buttonText = "Cube Spammer [g]", method =() => WorldMods.CubeSpam(), isTogglable = true, toolTip = "cubes!" },
                new ButtonInfo { buttonText = "Cube Gun", method =() => WorldMods.CubeGun(), isTogglable = true, toolTip = "cubes!" },
                new ButtonInfo { buttonText = "Target Spammer [g]", method =() => WorldMods.TargetSpam(), isTogglable = true, toolTip = "targets!" },
                new ButtonInfo { buttonText = "Target Gun", method =() => WorldMods.TargetGun(), isTogglable = true, toolTip = "targets!" },
                new ButtonInfo { buttonText = "Spawn Blue Lucy [m]", method =() => WorldMods.SpawnLucy(Color.blue), isTogglable = false, toolTip = "lucy!"},
                new ButtonInfo { buttonText = "Spawn Red Lucy [m]", method =() => WorldMods.SpawnLucy(Color.red), isTogglable = false, toolTip = "lucy!"},
                new ButtonInfo { buttonText = "Spawn Black Lucy [m]", method =() => WorldMods.SpawnLucy(Color.black), isTogglable = false, toolTip = "lucy!"},
                new ButtonInfo { buttonText = "Despawn Lucy [m]", method =() => WorldMods.DespawnLucy(), isTogglable = false, toolTip = "lucy!"},
                new ButtonInfo { buttonText = "Lucy Grab Player Gun [m]", method =() => WorldMods.LucyGrabGun(), isTogglable = true, toolTip = "lucy!"},
                new ButtonInfo { buttonText = "Lucy Gun [m]", method =() => WorldMods.LucyGun(), isTogglable = true, toolTip = "lucy!"},
                new ButtonInfo { buttonText = "Become Lucy [m]", method =() => WorldMods.BecomeLucy(), isTogglable = true, toolTip = "lucy!"},
                new ButtonInfo { buttonText = "Slow Lucy [m]", method =() => WorldMods.SlowLucy(), toolTip = "lucy!"},
                new ButtonInfo { buttonText = "Fast Lucy [m]", method =() => WorldMods.FastLucy(), isTogglable = false, toolTip = "lucy!"},
                new ButtonInfo { buttonText = "Fix Lucy [m]", method =() => WorldMods.FixLucy(), isTogglable = false,  toolTip = "lucy!"},
                new ButtonInfo { buttonText = "Disable QuitBox", method =() => WorldMods.DisableQuitbox(), disableMethod =() => WorldMods.OffQuitboxMod(), isTogglable = true, toolTip = "crazy!"},
                new ButtonInfo { buttonText = "Enemy Crash Blocker", enableMethod =() => WorldMods.EnemyAIBlocker = true, disableMethod =() => WorldMods.EnemyAIBlocker = false, isTogglable = true, toolTip = "no crashy crash"},
                new ButtonInfo { buttonText = "Teleport To Stump When Out Of Map", method =() => WorldMods.QuitboxMod(), disableMethod =() => WorldMods.OffQuitboxMod(), isTogglable = true, toolTip = "crazy!"},

            },

            new ButtonInfo[] { // Visual Mods | 5
                new ButtonInfo { buttonText = "Visual Mods", method =() => Instance.ChangeCat(false), isTogglable = false, toolTip = "Go back!" },
                new ButtonInfo { buttonText = "Clear Notifications", method =() => NotificationManager.ClearAllNotifications(), isTogglable = true, toolTip = "clear notifs!" },
                new ButtonInfo { buttonText = "Turning", method =() => VisualMods.Turning(), isTogglable = true, toolTip = "turning!" },
                new ButtonInfo { buttonText = "ESP", method =() => VisualMods.ESP(), disableMethod =() => VisualMods.DisableESP(), isTogglable = true, toolTip = "ESP!" },
                new ButtonInfo { buttonText = "Bone ESP", method =() => VisualMods.StartSkeleEsp(), disableMethod =() => VisualMods.EndSkeleEsp(), isTogglable = true, toolTip = "Shibas favorite!" },
                new ButtonInfo { buttonText = "Tracers", method =() => VisualMods.Tracers(), disableMethod =() => VisualMods.OFFTracers(), isTogglable = true, toolTip = "Very epic!" },
                new ButtonInfo { buttonText = "Box ESP", method =() => VisualMods.BoxEsp(), disableMethod =() => VisualMods.OFFBoxEsp(), isTogglable = true, toolTip = "Box esp!" },
                new ButtonInfo { buttonText = "Head ESP", method =() => VisualMods.HeadESP(), disableMethod =() => VisualMods.OffHeadESP(), isTogglable = true, toolTip = "Head esp!" },
            },

            new ButtonInfo[] { // Player Mods | 6
                new ButtonInfo { buttonText = "Player / Movement Mods", method =() => Instance.ChangeCat(false), isTogglable = false, toolTip = "Go back!" },
                new ButtonInfo { buttonText = "Speed Boost", method =() => PlayerMovement.SpeedBoost(), disableMethod =() => PlayerMovement.DisableSpeedBoost(), isTogglable = true, toolTip = "Speed boost!" },
                new ButtonInfo { buttonText = "Really Long Arms", method =() => PlayerMovement.ReallyArms(), disableMethod =() => PlayerMovement.ResetArms(), isTogglable = true, toolTip = "Really long arms!!" },
                new ButtonInfo { buttonText = "Platforms", method =() => PlayerMovement.Platforms(), isTogglable = true, toolTip = "Platforms!" },
                new ButtonInfo { buttonText = "Noclip [t]", method =() => PlayerMovement.Noclip(), isTogglable = true, toolTip = "Press trigger for noclip!" },
                new ButtonInfo { buttonText = "Fly", method =() => PlayerMovement.Fly(), isTogglable = true, toolTip = "Press secondary to fly!" },
                new ButtonInfo { buttonText = "Trigger Fly", method =() => PlayerMovement.TriggerFly(), isTogglable = true, toolTip = "Press trigger to fly!" },
                new ButtonInfo { buttonText = "Noclip Trigger Fly", method =() => PlayerMovement.NoclipTriggerFly(), isTogglable = true, toolTip = "Press trigger to fly!" },
                new ButtonInfo { buttonText = "Bark Fly", method =() => PlayerMovement.BarkFly(), disableMethod =() => PlayerMovement.OffBarkFly(), isTogglable = true, toolTip = "Just like bark!" },
                new ButtonInfo { buttonText = "Iron Monke", method =() => PlayerMovement.IronMonke(), isTogglable = true, toolTip = "ironman!" },
                new ButtonInfo { buttonText = "Slingshot Fly", method =() => PlayerMovement.SlingshotFly(), isTogglable = true, toolTip = "slingshot, from the OG menu!" },
                new ButtonInfo { buttonText = "Fast Slingshot Fly", method =() => PlayerMovement.FastSlingshotFly(), isTogglable = true, toolTip = "slingshot, from the OG menu!" },
                new ButtonInfo { buttonText = "Talk Through Siren [t]", method =() => PlayerMovement.SirenTalk(), isTogglable = true, toolTip = "siren!" },
                new ButtonInfo { buttonText = "Banana Car", method =() => PlayerMovement.BananaCar(), isTogglable = true, toolTip = "Car (joystick)!" },
                new ButtonInfo { buttonText = "TP Gun", method =() => PlayerMovement.TPGun(), isTogglable = true, toolTip = "Teleport to the pointer!" },
                new ButtonInfo { buttonText = "TP To Random", method =() => PlayerMovement.TPGun(), isTogglable = false, toolTip = "TP!" },
                new ButtonInfo { buttonText = "Auto Run [lg]", method =() => PlayerMovement.AutoRun(), isTogglable = true, toolTip = "Run silly!" },
                new ButtonInfo { buttonText = "Bhop [kingofnetflix]", method =() => PlayerMovement.Bhop(), isTogglable = true, toolTip = "Minecraft!" },
            },

            new ButtonInfo[] { // Legit Mods | 7
                new ButtonInfo { buttonText = "Legit Mods", method =() => Instance.ChangeCat(false), isTogglable = false, toolTip = "Go back!" },
                new ButtonInfo { buttonText = "Steam Long Arms", method = () => LegitMods.SteamArms(), disableMethod = () => LegitMods.DisableSteamArms(), isTogglable = true, toolTip = "Steam long arms!" },
                new ButtonInfo { buttonText = "60 HZ", method = () => LegitMods.HZ(), isTogglable = true, toolTip = "Slide!" },
                new ButtonInfo { buttonText = "Wall Walk [lg]", method = () => LegitMods.WallWalk(), isTogglable = true, toolTip = "Walk on walls!" },
                new ButtonInfo { buttonText = "Fake Oculus Menu [b]", method = () => LegitMods.FakeOculus(), isTogglable = true, toolTip = "Put your hands on your chest first!" },
                new ButtonInfo { buttonText = "Fake Lag", method = () => LegitMods.FakeLag(), isTogglable = true, toolTip = "Lag!" },
                new ButtonInfo { buttonText = "Slide Control", method = () => LegitMods.SlideControl(), disableMethod =() => LegitMods.OFFSlideControl(), isTogglable = true, toolTip = "Slide!" },
            },

            new ButtonInfo[] { // Rig Mods | 8
                new ButtonInfo { buttonText = "Rig Mods", method =() => Instance.ChangeCat(false), isTogglable = false, toolTip = "Go back!" },
                new ButtonInfo { buttonText = "Ghost Monke", method =() => RigMods.GhostMonkey(), disableMethod =() => RigMods.ResetRig(), isTogglable = true, toolTip = "Primary or smth to use!" },
                new ButtonInfo { buttonText = "Invis Monke", method =() => RigMods.InvisMonkey(), disableMethod =() => RigMods.ResetRig(), isTogglable = true, toolTip = "Trigger to invis!" },
                new ButtonInfo { buttonText = "Hold Rig", method =() => RigMods.HoldRig(), disableMethod =() => RigMods.ResetRig(), isTogglable = true, toolTip = "Grips!" },
                new ButtonInfo { buttonText = "Rig Gun", method =() => RigMods.RigGun(), disableMethod =() => RigMods.ResetRig(), isTogglable = true, toolTip = "Gun!" },
                new ButtonInfo { buttonText = "Follow Player Gun", method =() => RigMods.FollowPlayerGun(), disableMethod =() => RigMods.ResetRig(), isTogglable = true, toolTip = "Gun!" },
                new ButtonInfo { buttonText = "Lucy Random [rg]", method =() => RigMods.LucyRandom(), disableMethod =() => RigMods.ResetRig(), isTogglable = true, toolTip = "Become Lucy!" },
                new ButtonInfo { buttonText = "Lucy Gun", method =() => RigMods.LucyGun(), disableMethod =() => RigMods.ResetRig(), isTogglable = true, toolTip = "Gun!" },
                new ButtonInfo { buttonText = "Copy Gun", method =() => RigMods.CopyGun(), disableMethod =() => RigMods.ResetRig(), isTogglable = true, toolTip = "Copy gun!" },
                new ButtonInfo { buttonText = "Sex Gun", method =() => RigMods.SexGun(), disableMethod =() => RigMods.ResetRig(), isTogglable = true, toolTip = "Gun!" },
                new ButtonInfo { buttonText = "Look At Gun", method =() => RigMods.LookAtGun(), disableMethod =() => RigMods.ResetRig(), isTogglable = true, toolTip = "Closest!" },
                new ButtonInfo { buttonText = "Look At Closest", method =() => RigMods.LookAtClosest(), disableMethod =() => RigMods.ResetRig(), isTogglable = true, toolTip = "Closest!" },
                new ButtonInfo { buttonText = "Spin Bot [lg]", method =() => RigMods.SpinBot(), disableMethod =() => RigMods.ResetRig(), isTogglable = true, toolTip = "Spin!" },
                new ButtonInfo { buttonText = "T Pose [rg]", method =() => RigMods.Tpose(), disableMethod =() => RigMods.ResetRig(), isTogglable = true, toolTip = "T!" },
                new ButtonInfo { buttonText = "Helicoptor [lg]", method =() => RigMods.Helicopter(), disableMethod =() => RigMods.ResetRig(), isTogglable = true, toolTip = "vroom vroom!" },
                new ButtonInfo { buttonText = "Annoy Player Gun", method =() => RigMods.AnnoyGun(), disableMethod =() => RigMods.ResetRig(), isTogglable = true, toolTip = "annoy!" },
                new ButtonInfo { buttonText = "Halo Around Player Gun", method =() => RigMods.HaloGun(), disableMethod =() => RigMods.ResetRig(), isTogglable = true, toolTip = "annoy!" },
                new ButtonInfo { buttonText = "Jumpscare Gun", method =() => RigMods.JumpscareGun(), disableMethod =() => RigMods.ResetRig(), isTogglable = true, toolTip = "annoy!" },
                new ButtonInfo { buttonText = "Head Spin", method =() => RigMods.HeadSpin(), disableMethod =() => RigMods.OffHeadSpin(), isTogglable = true, toolTip = "Spin!" },
                new ButtonInfo { buttonText = "Head Roll", method =() => RigMods.HeadRoll(), disableMethod =() => RigMods.OffHeadRoll(), isTogglable = true, toolTip = "Roll!" },
                new ButtonInfo { buttonText = "Spaz Monkey", method =() => RigMods.SpazMonk(), isTogglable = true, toolTip = "Spaz!" },
                new ButtonInfo { buttonText = "Hand Spaz", method =() => RigMods.HandSpaz(), isTogglable = true, toolTip = "Spaz!" },
                new ButtonInfo { buttonText = "Head Spaz", method =() => RigMods.HeadSpaz(), isTogglable = true, toolTip = "Spaz!" },
                new ButtonInfo { buttonText = "Head Upsidedown", method =() => RigMods.HeadUpsidedown(), disableMethod =() => RigMods.OFFHeadUpsidedown(), isTogglable = true, toolTip = "Upsidedown!" },
                new ButtonInfo { buttonText = "Head Backwards", method =() => RigMods.HeadBackwards(), disableMethod =() => RigMods.OFFHeadBackwards(), isTogglable = true, toolTip = "Backwords!" },
            },

            new ButtonInfo[] { // Advantage Mods | 9
                new ButtonInfo { buttonText = "Advantage Mods", method =() => Instance.ChangeCat(false), isTogglable = false, toolTip = "Go back!" },
                new ButtonInfo { buttonText = "No Tag Freeze", method =() => AdvantageMods.NoTagFreeze(), isTogglable = true, toolTip = "Walky walk!" },
                new ButtonInfo { buttonText = "Uninfect Self", method = () => AdvantageMods.Untagself(), isTogglable = false, toolTip = "Untag Self!" },
                new ButtonInfo { buttonText = "Uninfect Gun", method = () => AdvantageMods.UntagGun(), isTogglable = true, toolTip = "Untag Gun!" },
                new ButtonInfo { buttonText = "Uninfect All", method = () => AdvantageMods.UntagAll(), isTogglable = false, toolTip = "Untag All!" },
                new ButtonInfo { buttonText = "Tag Gun", method =() => AdvantageMods.TagGun(), isTogglable = true, toolTip = "Tag Gun!" },
                new ButtonInfo { buttonText = "Tag All", method =() => AdvantageMods.TagAll(), isTogglable = true, toolTip = "Tag All!" },
                new ButtonInfo { buttonText = "Tag Aura", method =() => AdvantageMods.TagAura(), isTogglable = true, toolTip = "Tag Aura!" },
                new ButtonInfo { buttonText = "Tag Self", method =() => AdvantageMods.TagSelf(), isTogglable = true, toolTip = "Tag Self!" },
                new ButtonInfo { buttonText = "Anti Tag", method =() => AdvantageMods.AntiTag(), isTogglable = true, toolTip = "*weave*" },
            },

            new ButtonInfo[] { // Admin Mods | 10
                new ButtonInfo { buttonText = "Admin Mods", method =() => Instance.ChangeCat(false), isTogglable = false, toolTip = "Go back!" },
                new ButtonInfo { buttonText = "Get Console Users", method =() => Instance.GetMenuUsers(), isTogglable = false, toolTip = "Gets all users using console" },
                new ButtonInfo { buttonText = "Console Users NameTag", enableMethod =() => Console.ServerDataGenesis.instance.adminnametags = true, disableMethod =() => Console.ServerDataGenesis.instance.adminnametags = false, isTogglable = true, toolTip = "Enables the console nametags" },
                new ButtonInfo { buttonText = "Admin Quit All", method =() => Instance.ConsoleQuitAll(), isTogglable = false, toolTip = "Quits everyone using console" },
                new ButtonInfo { buttonText = "Admin Quit Gun", method =() => Instance.ConsoleQuitGun(), isTogglable = true, toolTip = "Quits who ever you shoot using console" },
                new ButtonInfo { buttonText = "Admin Discord Open All", method =() => Instance.ConsoleDiscordAll(), isTogglable = false, toolTip = "Opens the qolossal discord on the browser of everyone using console" },
                new ButtonInfo { buttonText = "Admin Discord Open Gun", method =() => Instance.ConsoleOpenDiscordGun(), isTogglable = true, toolTip = "Opens the qolossal discord on the browser of who ever you shoot using console" },
                new ButtonInfo { buttonText = "Admin Crash All", method =() => Instance.ConsoleCrashAll(), isTogglable = false, toolTip = "Crashes everyone who is using console" },
                new ButtonInfo { buttonText = "Admin Crash Gun", method =() => Instance.ConsoleCrashGun(), isTogglable = true, toolTip = "Crashes the person you shoot who is using console" },
                new ButtonInfo { buttonText = "Admin Kick All", method =() => Instance.ConsoleKickAll(), isTogglable = false, toolTip = "Kicks everyone using console"},
                new ButtonInfo { buttonText = "Admin Kick Gun", method =() => Instance.ConsoleKickGun(), isTogglable = true, toolTip = "Kicks who ever you shoot using console" },
                new ButtonInfo { buttonText = "Admin Fling All", method =() => Instance.ConsoleFlingAll(), isTogglable = false, toolTip = "Flings everyone using console" },
                new ButtonInfo { buttonText = "Admin Fling Gun", method =() => Instance.ConsoleFlingGun(), isTogglable = true, toolTip = "Flings who ever you shoot using console" },
                new ButtonInfo { buttonText = "Admin Bring All", method =() => Instance.ConsoleBringAll(), isTogglable = false, toolTip = "Brings everyone using console to you" },
                new ButtonInfo { buttonText = "Admin Bring Gun", method =() => Instance.ConsoleBringGun(), isTogglable = true, toolTip = "Brings whoever you shoot using console to you" },
                new ButtonInfo { buttonText = "Admin Ghost All", method =() => Instance.ConsoleGhostAll(), isTogglable = false, toolTip = "Makes everyone ghost monke" },
                new ButtonInfo { buttonText = "Admin Ghost Gun", method =() => Instance.ConsoleGhostGun(), isTogglable = true, toolTip = "Makes who ever you shoot ghost monke" },
                new ButtonInfo { buttonText = "Admin UnGhost All", method =() => Instance.ConsoleUnGhostAll(), isTogglable = false, toolTip = "Fixes everyones rig" },
                new ButtonInfo { buttonText = "Admin UnGhost Gun", method =() => Instance.ConsoleUnGhostGun(), isTogglable = true, toolTip = "Fixes who you shoot rig" },
                new ButtonInfo { buttonText = "Admin Disable Movement All", method =() => Instance.ConsoleDisableMovementAll(), isTogglable = false, toolTip = "Disables everyones movement using console" },
                new ButtonInfo { buttonText = "Admin Disable Movement Gun", method =() => Instance.ConsoleDisableMovementGun(), isTogglable = true, toolTip = "Disables who you shoot movement using console" },
                new ButtonInfo { buttonText = "Admin Enable Movement All", method =() => Instance.ConsoleEnableMovementAll(), isTogglable = false, toolTip = "Reanbles everyones movement using console" },
                new ButtonInfo { buttonText = "Admin Enable Movement Gun", method =() => Instance.ConsoleEnableMovementGun(), isTogglable = true, toolTip = "Reanbles who you shoot movement using console" },
                new ButtonInfo { buttonText = "Admin Mute All", method =() => Instance.ConsoleMuteAll(), isTogglable = false, toolTip = "Mutes everyone using console" },
                new ButtonInfo { buttonText = "Admin Mute Gun", method =() => Instance.ConsoleMuteGun(), isTogglable = true, toolTip = "Mutes who you shoot using console" },
                new ButtonInfo { buttonText = "Admin UnMute All", method =() => Instance.ConsoleUnMuteAll(), isTogglable = false, toolTip = "UnMutes everyone using console"},
                new ButtonInfo { buttonText = "Admin UnMute Gun", method =() => Instance.ConsoleUnMuteGun(), isTogglable = true, toolTip = "UnMutes who you shoot using console" },
                new ButtonInfo { buttonText = "Admin Network Player All", method =() => Instance.ConsoleNetworkPlayerAll(), isTogglable = false, toolTip = "Spawns a network player at people using console" },
                new ButtonInfo { buttonText = "Admin Network Player Gun", method =() => Instance.ConsoleNetworkPlayerGun(), isTogglable = true, toolTip = "Spawns a network player at who you shoot using console" },
                new ButtonInfo { buttonText = "Admin Target All", method =() => Instance.ConsoleTargetPlayerAll(), isTogglable = false, toolTip = "Spawns a stickable target at everyone using console" },
                new ButtonInfo { buttonText = "Admin Target Gun", method =() => Instance.ConsoleTargetPlayerGun(), isTogglable = true, toolTip = "Spawns a stickable target at who you shoot using console" },
                new ButtonInfo { buttonText = "Admin Change Name All", method =() => Instance.ConsoleChangeNameAll(), isTogglable = false, toolTip = "Changes everyones name using console" },
                new ButtonInfo { buttonText = "Admin Change Name Gun", method =() => Instance.ConsoleChangeNameGun(), isTogglable = true, toolTip = "Changes who you shoot name using console" },
                new ButtonInfo { buttonText = "Admin Restart Mic All", method =() => Instance.ConsoleRestartMicAll(), isTogglable = false, toolTip = "Makes everyones mic normal" },
                new ButtonInfo { buttonText = "Admin Restart Mic Gun", method =() => Instance.ConsoleRestartMicGun(), isTogglable = true, toolTip = "Makes who you shoot mic normal" },
                new ButtonInfo { buttonText = "Admin Disable Mods All", method =() => Instance.ConsolePanicAll(), isTogglable = false, toolTip = "Disables everyones mods who are using console" },
                new ButtonInfo { buttonText = "Admin Disable Mods Gun", method =() => Instance.ConsolePanicGUn(), isTogglable = true, toolTip = "Makes the person you shoot mods disable" },
            },
        };
    }
}